### ISSUE TITLE
Just get errors

### ISSUE THREAD

**Issue by Dan1jel** [jamescnowell/ticks#1]
This looks great but i can't get it to work. All i get is error in the termux 

```
ticks aapl goog
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ticks", line 33, in <module>
    sys.exit(load_entry_point('ticks==0.1.5', 'console_scripts', 'ticks')())
  File "/data/data/com.termux/files/usr/bin/ticks", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/ticks.py", line 4, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by jniq** [comment]
Thanks for letting me know.
It's been a while since I've used this, and I think the Yahoo finance API has moved as well.
I'll see what I can do about upgrading this.

**Comment by Dan1jel** [comment]
I see, well this would be perfekt to use. Easy not that much design, hut gives you the essentials. Thanks for looking in to this.
